data:
  client_split: 0.2
  dataset:
    name: adult
    path: ./data
  distribution:
    name: iid
  keep_test: true
  sampling_perc: 1.0
  server_split: 0.0
  server_test: true
  uniform_test: false
eval:
  eval_every: 1
  locals: true
  post_fit: true
  pre_fit: false
  server: true
exp:
  device: cpu
  seed: 42
  inmemory: true
logger:
  name: CsvLog
  log_dir: runs/adult_MLP_decentralized 
protocol:
  eligible_perc: 1.0
  n_clients: 10
  n_rounds: 50
