hyperparameters:
  client:
    batch_size: 64
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.001
      momentum: 0.9
      weight_decay: 1.0e-05
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: Adult_MLP
  net_args:
    hidden1: 64
    hidden2: 32
  server:
    weighted: true
    lr: 1.0
name: fluke.algorithms.decentralized.DecentralizedFedAvg
