hyperparameters:
  client:
    batch_size: 32
    local_epochs: 5
    loss: CrossEntropyLoss
    optimizer:
      lr: 0.1
    scheduler:
      gamma: 1
      step_size: 1
  model: MNIST_2NN
  server:
    global_step: 2
name: fluke.algorithms.scaffold.SCAFFOLD
